export const horarios = [
  {
    id: 1,
    title: "Salsa - Nivel Principiante",
    time: "19:00",
    instructor: "María Rodríguez",
    type: "clase",
    day: "Lunes",
  },
  {
    id: 2,
    title: "Bachata - Nivel Intermedio",
    time: "20:00",
    instructor: "Carlos Martínez",
    type: "clase",
    day: "Martes",
  },
  {
    id: 3,
    title: "Merengue - Todos los niveles",
    time: "20:00",
    instructor: "María Rodríguez",
    type: "clase",
    day: "Lunes",
  },
  {
    id: 4,
    title: "Rumba/Timba - Avanzado",
    time: "18:00",
    instructor: "Ana García",
    type: "clase",
    day: "Viernes",
  },
  {
    id: 5,
    title: "Cha Cha Cha - Principiantes",
    time: "19:00",
    instructor: "Carlos Martínez",
    type: "clase",
    day: "Martes",
  },
  {
    id: 6,
    title: "Salsa - Nivel Intermedio",
    time: "19:00",
    instructor: "María Rodríguez",
    type: "clase",
    day: "Miércoles",
  },
  {
    id: 7,
    title: "Bachata - Nivel Avanzado",
    time: "20:00",
    instructor: "Carlos Martínez",
    type: "clase",
    day: "Jueves",
  },
  {
    id: 8,
    title: "Salsa - Nivel Principiante",
    time: "10:00",
    instructor: "María Rodríguez",
    type: "clase",
    day: "Sábado",
  },
  {
    id: 9,
    title: "Bachata - Nivel Intermedio",
    time: "11:00",
    instructor: "Carlos Martínez",
    type: "clase",
    day: "Sábado",
  },
  {
    id: 10,
    title: "Rumba/Timba - Intermedios",
    time: "15:00",
    instructor: "Ana García",
    type: "clase",
    day: "Domingo",
  },
];
